-- Current public table and index backup
-- Generated from Supabase catalog on 2026-08-30.
-- Contains structure only; no application data.
-- Run only when restoring into an empty Supabase project.

begin;

create extension if not exists pgcrypto;

create table public."admin_users" (
  "id" uuid not null,
  "name" text not null,
  "role" text default 'admin'::text not null,
  "status" text default 'active'::text not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."attendance" (
  "id" bigint generated always as identity not null,
  "user_id" uuid not null,
  "work_date" date default CURRENT_DATE not null,
  "check_in_time" timestamp with time zone,
  "check_out_time" timestamp with time zone,
  "check_in_latitude" numeric,
  "check_in_longitude" numeric,
  "check_out_latitude" numeric,
  "check_out_longitude" numeric,
  "status" text default 'working'::text,
  "memo" text,
  "created_at" timestamp with time zone default now(),
  "workplace_id" bigint,
  "work_shift_id" bigint,
  "scheduled_check_out_time" timestamp with time zone,
  "auto_close_grace_minutes" integer default 240 not null,
  "is_auto_closed" boolean default false not null,
  "auto_closed_at" timestamp with time zone,
  "auto_close_reason" text
);

create table public."attendance_edit_history" (
  "id" bigint generated by default as identity not null,
  "attendance_id" bigint not null,
  "user_id" uuid,
  "work_date" date not null,
  "old_check_in_time" timestamp with time zone,
  "new_check_in_time" timestamp with time zone,
  "old_check_out_time" timestamp with time zone,
  "new_check_out_time" timestamp with time zone,
  "old_status" text,
  "new_status" text,
  "edit_type" text not null,
  "edit_reason" text not null,
  "memo" text,
  "editor_name" text,
  "created_at" timestamp with time zone default now() not null
);

create table public."attendance_issue_actions" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "attendance_id" bigint,
  "issue_date" date not null,
  "issue_type" text not null,
  "action_status" text,
  "reason" text,
  "memo" text,
  "created_by" uuid default auth.uid(),
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."attendance_location_attempts" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "attempt_date" date not null,
  "attempted_at" timestamp with time zone default now() not null,
  "latitude" numeric not null,
  "longitude" numeric not null,
  "nearest_workplace_id" bigint,
  "distance_m" double precision,
  "allowed_radius" integer,
  "created_at" timestamp with time zone default now() not null
);

create table public."checklist_items" (
  "id" uuid default gen_random_uuid() not null,
  "label" text not null,
  "active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null
);

create table public."cleaning_checklist_submissions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "workplace_id" text not null,
  "work_date" date default CURRENT_DATE not null,
  "checked_items" jsonb default '[]'::jsonb not null,
  "note" text,
  "created_at" timestamp with time zone default now() not null
);

create table public."employee_custom_checklist_items" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "workplace_id" text not null,
  "label" text not null,
  "created_at" timestamp with time zone default now() not null
);

create table public."employee_daily_notes" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "note_date" date not null,
  "content" text default ''::text not null,
  "created_by" uuid default auth.uid(),
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "day_type" text default 'normal'::text not null
);

create table public."employee_departments" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "description" text,
  "sort_order" integer default 0 not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."employee_notifications" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "type" text not null,
  "title" text not null,
  "content" text default ''::text not null,
  "related_id" text,
  "read_at" timestamp with time zone,
  "created_at" timestamp with time zone default now() not null
);

create table public."employee_request_attachments" (
  "id" uuid default gen_random_uuid() not null,
  "request_id" uuid not null,
  "file_name" text not null,
  "mime_type" text not null,
  "file_size" integer not null,
  "file_data" bytea not null,
  "created_at" timestamp with time zone default now() not null
);

create table public."employee_requests" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "request_type" text not null,
  "title" text not null,
  "content" text not null,
  "status" text default 'pending'::text not null,
  "created_at" timestamp with time zone default now(),
  "start_date" date,
  "end_date" date,
  "workplace_id" text,
  "admin_note" text,
  "resolved_at" timestamp with time zone,
  "resolved_by" uuid
);

create table public."employee_sessions" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "session_token" text not null,
  "created_at" timestamp with time zone default now() not null,
  "expires_at" timestamp with time zone default (now() + '30 days'::interval) not null,
  "approval_status" text default 'pending'::text not null,
  "approval_requested_at" timestamp with time zone default now(),
  "approved_at" timestamp with time zone,
  "approved_by" uuid,
  "revoked_at" timestamp with time zone,
  "revoked_reason" text
);

create table public."employee_uploads" (
  "id" uuid default gen_random_uuid() not null,
  "user_id" uuid not null,
  "upload_type" text not null,
  "request_id" uuid,
  "checklist_submission_id" uuid,
  "bucket_id" text default 'employee-uploads'::text not null,
  "object_path" text not null,
  "original_name" text not null,
  "mime_type" text not null,
  "file_size" integer not null,
  "created_at" timestamp with time zone default now() not null
);

create table public."job_positions" (
  "id" bigint generated by default as identity not null,
  "name" text not null,
  "description" text,
  "sort_order" integer default 0 not null,
  "is_active" boolean default true not null,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."login_requests" (
  "id" bigint generated always as identity not null,
  "name" text not null,
  "phone" text not null,
  "status" text default 'pending'::text,
  "memo" text,
  "created_at" timestamp with time zone default now()
);

create table public."notices" (
  "id" bigint generated always as identity not null,
  "title" text not null,
  "content" text not null,
  "is_active" boolean default true,
  "created_at" timestamp with time zone default now(),
  "status" text default '게시중'::text,
  "category" text default '전체공지'::text,
  "target" text default '전체 직원'::text,
  "important" boolean default false,
  "views" integer default 0,
  "published_at" timestamp with time zone default now(),
  "updated_at" timestamp with time zone default now()
);

create table public."photo_storage_settings" (
  "id" smallint default 1 not null,
  "storage_limit_bytes" bigint default 838860800 not null,
  "retention_days" integer default 365 not null,
  "updated_at" timestamp with time zone default now() not null
);

create table public."users" (
  "id" uuid default gen_random_uuid() not null,
  "name" text not null,
  "role" text default 'employee'::text,
  "created_at" timestamp with time zone default now(),
  "email" text,
  "phone" text,
  "department" text,
  "position" text,
  "status" text default 'pending'::text,
  "memo" text,
  "updated_at" timestamp with time zone default now(),
  "login_type" text default 'google'::text,
  "approved_at" timestamp with time zone,
  "employee_code" text,
  "auth_id" uuid,
  "workplace_id" bigint,
  "app_role" text default 'employee'::text,
  "app_approval_status" text default 'not_requested'::text,
  "login_requested_at" timestamp with time zone,
  "app_approved_at" timestamp with time zone,
  "app_approved_by" uuid
);

create table public."work_logs" (
  "id" bigint generated always as identity not null,
  "user_id" uuid not null,
  "workplace_id" bigint,
  "title" text not null,
  "content" text,
  "photo_url" text,
  "created_at" timestamp with time zone default now()
);

create table public."work_shifts" (
  "id" bigint generated by default as identity not null,
  "workplace_id" bigint not null,
  "name" text not null,
  "start_time" time without time zone not null,
  "end_time" time without time zone not null,
  "break_minutes" integer default 0 not null,
  "is_active" boolean default true not null,
  "sort_order" integer default 0 not null,
  "memo" text,
  "created_at" timestamp with time zone default now() not null,
  "updated_at" timestamp with time zone default now() not null,
  "auto_close_grace_minutes" integer default 240 not null
);

create table public."workplace_checklist_items" (
  "workplace_id" text not null,
  "item_id" uuid not null,
  "sort_order" integer default 0 not null
);

create table public."workplace_users" (
  "id" bigint generated always as identity not null,
  "workplace_id" bigint not null,
  "user_id" uuid not null,
  "created_at" timestamp with time zone default now(),
  "start_date" date,
  "end_date" date,
  "days_of_week" text[],
  "memo" text,
  "work_start_time" time without time zone,
  "work_end_time" time without time zone,
  "use_workplace_schedule" boolean default true not null,
  "work_shift_id" bigint
);

create table public."workplaces" (
  "id" bigint generated always as identity not null,
  "name" text not null,
  "address" text,
  "latitude" numeric not null,
  "longitude" numeric not null,
  "radius_m" integer default 100 not null,
  "is_active" boolean default true,
  "created_at" timestamp with time zone default now(),
  "default_days_of_week" text[],
  "default_start_time" time without time zone,
  "default_end_time" time without time zone
);

-- Primary keys, unique constraints, and checks.

alter table public."admin_users"
  add constraint "admin_users_pkey"
  PRIMARY KEY (id);

alter table public."admin_users"
  add constraint "admin_users_role_check"
  CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text]));

alter table public."admin_users"
  add constraint "admin_users_status_check"
  CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text]));

alter table public."attendance"
  add constraint "attendance_pkey"
  PRIMARY KEY (id);

alter table public."attendance_edit_history"
  add constraint "attendance_edit_history_pkey"
  PRIMARY KEY (id);

alter table public."attendance_issue_actions"
  add constraint "attendance_issue_actions_pkey"
  PRIMARY KEY (id);

alter table public."attendance_issue_actions"
  add constraint "attendance_issue_actions_type_check"
  CHECK (issue_type = ANY (ARRAY['late'::text, 'absent'::text, 'location_error'::text]));

alter table public."attendance_issue_actions"
  add constraint "attendance_issue_actions_unique"
  UNIQUE (user_id, issue_date, issue_type);

alter table public."attendance_location_attempts"
  add constraint "attendance_location_attempts_pkey"
  PRIMARY KEY (id);

alter table public."checklist_items"
  add constraint "checklist_items_label_key"
  UNIQUE (label);

alter table public."checklist_items"
  add constraint "checklist_items_pkey"
  PRIMARY KEY (id);

alter table public."cleaning_checklist_submissions"
  add constraint "cleaning_checklist_submissions_pkey"
  PRIMARY KEY (id);

alter table public."employee_custom_checklist_items"
  add constraint "employee_custom_checklist_items_pkey"
  PRIMARY KEY (id);

alter table public."employee_daily_notes"
  add constraint "employee_daily_notes_day_type_check"
  CHECK (day_type = ANY (ARRAY['normal'::text, 'annual_leave'::text]));

alter table public."employee_daily_notes"
  add constraint "employee_daily_notes_pkey"
  PRIMARY KEY (id);

alter table public."employee_daily_notes"
  add constraint "employee_daily_notes_user_id_note_date_key"
  UNIQUE (user_id, note_date);

alter table public."employee_departments"
  add constraint "employee_departments_pkey"
  PRIMARY KEY (id);

alter table public."employee_notifications"
  add constraint "employee_notifications_pkey"
  PRIMARY KEY (id);

alter table public."employee_request_attachments"
  add constraint "employee_request_attachments_pkey"
  PRIMARY KEY (id);

alter table public."employee_requests"
  add constraint "employee_requests_pkey"
  PRIMARY KEY (id);

alter table public."employee_sessions"
  add constraint "employee_sessions_approval_status_check"
  CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'revoked'::text]));

alter table public."employee_sessions"
  add constraint "employee_sessions_pkey"
  PRIMARY KEY (id);

alter table public."employee_sessions"
  add constraint "employee_sessions_session_token_key"
  UNIQUE (session_token);

alter table public."employee_uploads"
  add constraint "employee_uploads_file_size_check"
  CHECK (file_size > 0 AND file_size <= 5242880);

alter table public."employee_uploads"
  add constraint "employee_uploads_mime_type_check"
  CHECK (mime_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text]));

alter table public."employee_uploads"
  add constraint "employee_uploads_object_path_key"
  UNIQUE (object_path);

alter table public."employee_uploads"
  add constraint "employee_uploads_one_parent_check"
  CHECK (num_nonnulls(request_id, checklist_submission_id) = 1);

alter table public."employee_uploads"
  add constraint "employee_uploads_pkey"
  PRIMARY KEY (id);

alter table public."employee_uploads"
  add constraint "employee_uploads_upload_type_check"
  CHECK (upload_type = ANY (ARRAY['employee_request'::text, 'cleaning_checklist'::text]));

alter table public."job_positions"
  add constraint "job_positions_name_key"
  UNIQUE (name);

alter table public."job_positions"
  add constraint "job_positions_name_not_empty"
  CHECK (NULLIF(TRIM(BOTH FROM name), ''::text) IS NOT NULL);

alter table public."job_positions"
  add constraint "job_positions_pkey"
  PRIMARY KEY (id);

alter table public."login_requests"
  add constraint "login_requests_pkey"
  PRIMARY KEY (id);

alter table public."notices"
  add constraint "notices_pkey"
  PRIMARY KEY (id);

alter table public."photo_storage_settings"
  add constraint "photo_retention_days_check"
  CHECK (retention_days >= 1 AND retention_days <= 3650);

alter table public."photo_storage_settings"
  add constraint "photo_storage_limit_check"
  CHECK (storage_limit_bytes >= 104857600);

alter table public."photo_storage_settings"
  add constraint "photo_storage_settings_id_check"
  CHECK (id = 1);

alter table public."photo_storage_settings"
  add constraint "photo_storage_settings_pkey"
  PRIMARY KEY (id);

alter table public."users"
  add constraint "users_auth_id_key"
  UNIQUE (auth_id);

alter table public."users"
  add constraint "users_employee_code_key"
  UNIQUE (employee_code);

alter table public."users"
  add constraint "users_pkey"
  PRIMARY KEY (id);

alter table public."work_logs"
  add constraint "work_logs_pkey"
  PRIMARY KEY (id);

alter table public."work_shifts"
  add constraint "work_shifts_break_minutes_check"
  CHECK (break_minutes >= 0 AND break_minutes <= 720);

alter table public."work_shifts"
  add constraint "work_shifts_name_not_empty"
  CHECK (NULLIF(TRIM(BOTH FROM name), ''::text) IS NOT NULL);

alter table public."work_shifts"
  add constraint "work_shifts_pkey"
  PRIMARY KEY (id);

alter table public."work_shifts"
  add constraint "work_shifts_workplace_name_unique"
  UNIQUE (workplace_id, name);

alter table public."workplace_checklist_items"
  add constraint "workplace_checklist_items_pkey"
  PRIMARY KEY (workplace_id, item_id);

alter table public."workplace_users"
  add constraint "workplace_users_pkey"
  PRIMARY KEY (id);

alter table public."workplace_users"
  add constraint "workplace_users_work_time_check"
  CHECK (work_start_time IS NULL AND work_end_time IS NULL OR work_start_time IS NOT NULL AND work_end_time IS NOT NULL AND work_start_time < work_end_time);

alter table public."workplace_users"
  add constraint "workplace_users_workplace_id_user_id_key"
  UNIQUE (workplace_id, user_id);

alter table public."workplaces"
  add constraint "workplaces_default_work_time_check"
  CHECK (default_start_time IS NULL AND default_end_time IS NULL OR default_start_time IS NOT NULL AND default_end_time IS NOT NULL AND default_start_time < default_end_time);

alter table public."workplaces"
  add constraint "workplaces_pkey"
  PRIMARY KEY (id);

-- Foreign keys are added after every table exists.

alter table public."admin_users"
  add constraint "admin_users_id_fkey"
  FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table public."attendance"
  add constraint "attendance_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id);

alter table public."attendance"
  add constraint "attendance_work_shift_id_fkey"
  FOREIGN KEY (work_shift_id) REFERENCES work_shifts(id) ON DELETE SET NULL;

alter table public."attendance"
  add constraint "attendance_workplace_id_fkey"
  FOREIGN KEY (workplace_id) REFERENCES workplaces(id);

alter table public."attendance_edit_history"
  add constraint "attendance_edit_history_attendance_id_fkey"
  FOREIGN KEY (attendance_id) REFERENCES attendance(id) ON DELETE CASCADE;

alter table public."attendance_edit_history"
  add constraint "attendance_edit_history_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;

alter table public."attendance_issue_actions"
  add constraint "attendance_issue_actions_attendance_id_fkey"
  FOREIGN KEY (attendance_id) REFERENCES attendance(id) ON DELETE SET NULL;

alter table public."attendance_issue_actions"
  add constraint "attendance_issue_actions_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."attendance_location_attempts"
  add constraint "attendance_location_attempts_nearest_workplace_id_fkey"
  FOREIGN KEY (nearest_workplace_id) REFERENCES workplaces(id) ON DELETE SET NULL;

alter table public."attendance_location_attempts"
  add constraint "attendance_location_attempts_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."cleaning_checklist_submissions"
  add constraint "cleaning_checklist_submissions_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."employee_custom_checklist_items"
  add constraint "employee_custom_checklist_items_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."employee_daily_notes"
  add constraint "employee_daily_notes_created_by_fkey"
  FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;

alter table public."employee_daily_notes"
  add constraint "employee_daily_notes_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."employee_notifications"
  add constraint "employee_notifications_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."employee_request_attachments"
  add constraint "employee_request_attachments_request_id_fkey"
  FOREIGN KEY (request_id) REFERENCES employee_requests(id) ON DELETE CASCADE;

alter table public."employee_sessions"
  add constraint "employee_sessions_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."employee_uploads"
  add constraint "employee_uploads_checklist_submission_id_fkey"
  FOREIGN KEY (checklist_submission_id) REFERENCES cleaning_checklist_submissions(id) ON DELETE CASCADE;

alter table public."employee_uploads"
  add constraint "employee_uploads_request_id_fkey"
  FOREIGN KEY (request_id) REFERENCES employee_requests(id) ON DELETE CASCADE;

alter table public."employee_uploads"
  add constraint "employee_uploads_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."users"
  add constraint "users_auth_id_fkey"
  FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON DELETE SET NULL;

alter table public."users"
  add constraint "users_workplace_id_fkey"
  FOREIGN KEY (workplace_id) REFERENCES workplaces(id) ON DELETE SET NULL;

alter table public."work_logs"
  add constraint "work_logs_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."work_logs"
  add constraint "work_logs_workplace_id_fkey"
  FOREIGN KEY (workplace_id) REFERENCES workplaces(id);

alter table public."work_shifts"
  add constraint "work_shifts_workplace_id_fkey"
  FOREIGN KEY (workplace_id) REFERENCES workplaces(id) ON DELETE CASCADE;

alter table public."workplace_checklist_items"
  add constraint "workplace_checklist_items_item_id_fkey"
  FOREIGN KEY (item_id) REFERENCES checklist_items(id) ON DELETE CASCADE;

alter table public."workplace_users"
  add constraint "workplace_users_user_id_fkey"
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

alter table public."workplace_users"
  add constraint "workplace_users_work_shift_id_fkey"
  FOREIGN KEY (work_shift_id) REFERENCES work_shifts(id) ON DELETE SET NULL;

alter table public."workplace_users"
  add constraint "workplace_users_workplace_id_fkey"
  FOREIGN KEY (workplace_id) REFERENCES workplaces(id) ON DELETE CASCADE;

-- Standalone indexes.

CREATE INDEX attendance_open_record_idx ON public.attendance USING btree (user_id, check_in_time DESC) WHERE ((check_in_time IS NOT NULL) AND (check_out_time IS NULL));

CREATE INDEX attendance_edit_history_attendance_id_idx ON public.attendance_edit_history USING btree (attendance_id);

CREATE INDEX attendance_edit_history_created_at_idx ON public.attendance_edit_history USING btree (created_at DESC);

CREATE INDEX attendance_edit_history_user_id_idx ON public.attendance_edit_history USING btree (user_id);

CREATE INDEX attendance_edit_history_work_date_idx ON public.attendance_edit_history USING btree (work_date);

CREATE INDEX attendance_location_attempts_date_idx ON public.attendance_location_attempts USING btree (attempt_date, attempted_at DESC);

CREATE INDEX attendance_location_attempts_user_idx ON public.attendance_location_attempts USING btree (user_id, attempt_date);

CREATE UNIQUE INDEX employee_daily_notes_user_date_unique ON public.employee_daily_notes USING btree (user_id, note_date);

CREATE UNIQUE INDEX employee_departments_name_key ON public.employee_departments USING btree (lower(TRIM(BOTH FROM name)));

CREATE INDEX employee_request_attachments_request_id_idx ON public.employee_request_attachments USING btree (request_id);

CREATE INDEX employee_sessions_user_approval_idx ON public.employee_sessions USING btree (user_id, approval_status, created_at DESC);

CREATE INDEX employee_uploads_checklist_submission_id_idx ON public.employee_uploads USING btree (checklist_submission_id);

CREATE UNIQUE INDEX employee_uploads_object_path_unique ON public.employee_uploads USING btree (object_path);

CREATE INDEX employee_uploads_request_id_idx ON public.employee_uploads USING btree (request_id);

CREATE INDEX employee_uploads_user_id_idx ON public.employee_uploads USING btree (user_id);

CREATE INDEX job_positions_active_sort_idx ON public.job_positions USING btree (is_active, sort_order, id);

CREATE UNIQUE INDEX job_positions_name_lower_unique_idx ON public.job_positions USING btree (lower(TRIM(BOTH FROM name)));

CREATE INDEX work_shifts_active_idx ON public.work_shifts USING btree (is_active, sort_order, id);

CREATE INDEX work_shifts_workplace_id_idx ON public.work_shifts USING btree (workplace_id);

CREATE UNIQUE INDEX workplace_users_user_workplace_unique ON public.workplace_users USING btree (user_id, workplace_id);

CREATE INDEX workplace_users_work_shift_id_idx ON public.workplace_users USING btree (work_shift_id);

-- Enable RLS before API privileges are restored.

alter table public."admin_users" enable row level security;
alter table public."admin_users" no force row level security;

alter table public."attendance" enable row level security;
alter table public."attendance" no force row level security;

alter table public."attendance_edit_history" enable row level security;
alter table public."attendance_edit_history" no force row level security;

alter table public."attendance_issue_actions" enable row level security;
alter table public."attendance_issue_actions" no force row level security;

alter table public."attendance_location_attempts" enable row level security;
alter table public."attendance_location_attempts" no force row level security;

alter table public."checklist_items" enable row level security;
alter table public."checklist_items" no force row level security;

alter table public."cleaning_checklist_submissions" enable row level security;
alter table public."cleaning_checklist_submissions" no force row level security;

alter table public."employee_custom_checklist_items" enable row level security;
alter table public."employee_custom_checklist_items" no force row level security;

alter table public."employee_daily_notes" enable row level security;
alter table public."employee_daily_notes" no force row level security;

alter table public."employee_departments" enable row level security;
alter table public."employee_departments" no force row level security;

alter table public."employee_notifications" enable row level security;
alter table public."employee_notifications" no force row level security;

alter table public."employee_request_attachments" enable row level security;
alter table public."employee_request_attachments" no force row level security;

alter table public."employee_requests" enable row level security;
alter table public."employee_requests" no force row level security;

alter table public."employee_sessions" enable row level security;
alter table public."employee_sessions" no force row level security;

alter table public."employee_uploads" enable row level security;
alter table public."employee_uploads" no force row level security;

alter table public."job_positions" enable row level security;
alter table public."job_positions" no force row level security;

alter table public."login_requests" enable row level security;
alter table public."login_requests" no force row level security;

alter table public."notices" enable row level security;
alter table public."notices" no force row level security;

alter table public."photo_storage_settings" enable row level security;
alter table public."photo_storage_settings" no force row level security;

alter table public."users" enable row level security;
alter table public."users" no force row level security;

alter table public."work_logs" enable row level security;
alter table public."work_logs" no force row level security;

alter table public."work_shifts" enable row level security;
alter table public."work_shifts" no force row level security;

alter table public."workplace_checklist_items" enable row level security;
alter table public."workplace_checklist_items" no force row level security;

alter table public."workplace_users" enable row level security;
alter table public."workplace_users" no force row level security;

alter table public."workplaces" enable row level security;
alter table public."workplaces" no force row level security;

-- Remove Supabase default table privileges, then restore the safe subset.
revoke all on all tables in schema public from anon, authenticated;

grant delete, insert, select, update on table public."admin_users" to anon;
grant delete, insert, select, update on table public."admin_users" to authenticated;
grant delete, insert, select, update on table public."attendance" to anon;
grant delete, insert, select, update on table public."attendance" to authenticated;
grant delete, insert, select, update on table public."attendance_edit_history" to anon;
grant delete, insert, select, update on table public."attendance_edit_history" to authenticated;
grant delete, insert, select, update on table public."checklist_items" to anon;
grant delete, insert, select, update on table public."checklist_items" to authenticated;
grant delete, insert, select, update on table public."cleaning_checklist_submissions" to anon;
grant delete, insert, select, update on table public."cleaning_checklist_submissions" to authenticated;
grant delete, insert, select, update on table public."employee_custom_checklist_items" to anon;
grant delete, insert, select, update on table public."employee_custom_checklist_items" to authenticated;
grant delete, insert, select, update on table public."employee_daily_notes" to anon;
grant delete, insert, select, update on table public."employee_daily_notes" to authenticated;
grant delete, insert, select, update on table public."employee_departments" to anon;
grant delete, insert, select, update on table public."employee_departments" to authenticated;
grant delete, insert, select, update on table public."employee_notifications" to anon;
grant delete, insert, select, update on table public."employee_notifications" to authenticated;
grant delete, insert, select, update on table public."employee_requests" to anon;
grant delete, insert, select, update on table public."employee_requests" to authenticated;
grant delete, insert, select, update on table public."employee_sessions" to anon;
grant delete, insert, select, update on table public."employee_sessions" to authenticated;
grant delete, insert, select, update on table public."employee_uploads" to authenticated;
grant delete, insert, select, update on table public."job_positions" to anon;
grant delete, insert, select, update on table public."job_positions" to authenticated;
grant delete, insert, select, update on table public."login_requests" to anon;
grant delete, insert, select, update on table public."login_requests" to authenticated;
grant delete, insert, select, update on table public."notices" to anon;
grant delete, insert, select, update on table public."notices" to authenticated;
grant delete, insert, select, update on table public."photo_storage_settings" to authenticated;
grant delete, insert, select, update on table public."users" to anon;
grant delete, insert, select, update on table public."users" to authenticated;
grant delete, insert, select, update on table public."work_logs" to anon;
grant delete, insert, select, update on table public."work_logs" to authenticated;
grant delete, insert, select, update on table public."work_shifts" to anon;
grant delete, insert, select, update on table public."work_shifts" to authenticated;
grant delete, insert, select, update on table public."workplace_checklist_items" to anon;
grant delete, insert, select, update on table public."workplace_checklist_items" to authenticated;
grant delete, insert, select, update on table public."workplace_users" to anon;
grant delete, insert, select, update on table public."workplace_users" to authenticated;
grant delete, insert, select, update on table public."workplaces" to anon;
grant delete, insert, select, update on table public."workplaces" to authenticated;

-- Prevent dangerous privileges on tables created in the future.
alter default privileges in schema public
  revoke truncate, references, trigger on tables
  from anon, authenticated;

commit;
